django_basic/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # url of admin
    path('admin/', admin.site.urls),
    # url of register form
    path("", include('personal_finance.urls', namespace='personal_finance')),
]

personal_finance/urls.py
from django.urls import path
from .views import create_transaction, register, application, login_view, create_category, logout_view
from django.contrib.auth.decorators import login_required


app_name = 'personal_finance'

urlpatterns = [
    # url of register form
    path('', register, name='register'),
    # url of login form
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    # url of application for user
    path('application/<str:uuid>/',
         login_required(application, login_url="/login/"), name='application'),
    # url for category
    path('create_category/', login_required(create_category,
         login_url="/login/"), name='create_category'),
    # url for transaction
    path('create_transaction/',
         login_required(create_transaction, login_url="/login/"), name='create_transaction'),
]

personal_finance/models/category.py
from django.db import models
from .user import User


class Category(models.Model):
    """
        this class create the category with the foreign key of the user

    Args:
        models (_type_): Model
    """

    date = models.DateTimeField(auto_now=True)
    category_name = models.CharField(max_length=50)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.category_name

personal_finance/models/transaction.py
from django.db import models
from .user import User
from .category import Category


class Transaction(models.Model):
    """
        creates the transaction template with the foreign key of the user_uuid and the category
    """
    class TypeChoice(models.Choices):
        """
        this class handles the types or choices

        Args:
            models: Choices
        """

        income = 0
        expenditures = 1

    name = models.CharField(max_length=50, null=False, blank=False)
    budget_id = models.AutoField(primary_key=True, unique=True)
    type = models.IntegerField(
        choices=TypeChoice.choices, default=TypeChoice.income)

    transaction_date = models.DateField(auto_now=True)
    amount = models.FloatField()

    user_uuid = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE)

personal_finance/models/user.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager as DjangoUserManager


class UserManager(DjangoUserManager):
    """_
        create model UserManager

    Args:
        DjangoUserManager (_type_): Create and save a user with the given username, email, and password.
    """
    def create_user(self, username, type_user="", first_name="", last_name="", email="", password=None):
        return super().create_user(
            username,
            email,
            password,
            type_user=type_user,
            first_name=first_name,
            last_name=last_name,
        )


    def create_superuser(self, username, first_name="", last_name="", email="", password=None):
        return super().create_superuser(
            username,
            email,
            password,
            first_name=first_name,
            last_name=last_name,
        )


class User(AbstractUser):
    """_summary_

    Args:
        AbstractUser (_type_):
            An abstract base class implementing a fully featured User model with
            admin-compliant permissions.

            Username and password are required. Other fields are optional.
    """

    uuid = models.UUIDField(unique=True, default=uuid.uuid4,
                            editable=False, db_index=True, primary_key=True)
    phone = models.CharField(max_length=20, blank=True)

    objects = UserManager()
    USERNAME_FIELD = "username"

personal_finance/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models.user import User


class RegisterForm(UserCreationForm):
    """
    this class creates the registration form with its meta class

    Args:
        UserCreationForm: class template form
    """

    username = forms.CharField(max_length=30, required=True, label="Username", widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your Username'}))
    first_name = forms.CharField(max_length=30, required=False, label="First Name",
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your first name'}))
    last_name = forms.CharField(max_length=30, required=False, label="Last Name",
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your last name'}))
    email = forms.EmailField(required=False, label="Email",
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}))
    phone = forms.CharField(required=False, label="Number Phone",
                            widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter your number phone'}))
    password1 = forms.CharField(label="Password", widget=(forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your password'})))
    password2 = forms.CharField(
        label="Confirm Password", widget=(forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm your password'})))

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "phone",
            "password1",
            "password2",
        ]
        help_texts = {k: None for k in fields}

personal_finance/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from personal_finance.models.transaction import Transaction
from .forms import RegisterForm
from personal_finance.models import User, Category, Transaction
from django.contrib.auth import authenticate, login, logout

# Create your views here.

"""
    if request.user.is_authenticated():
    username = request.user.username
"""


def register(request):
    """_summary_
        this function validates if the form sends a POST method, if the condition is fulfilled it saves the form data in the database.
    it gets the user and the uuid of the user to redirect to the app of that specific user and sends a message if everything is fulfilled successfully. if it is not a POST method it only saves the form and sends it by context.

    Args:
        request: the request object

    Returns:
        render: returns a template of the registry with the forms
    """

    if(request.method == "POST"):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            user = User.objects.get(username=username)
            uuid = user.uuid
            messages.success(request, f"Account created for {username}!")
            login(request, user)
            return redirect(f'/application/{uuid}')
    else:
        form = RegisterForm()
    context = {"form": form}
    return render(request, 'register.html', context)


def login_view(request):
    """
        this function checks the request is a GET method, if the condition is met it returns the record with an empty context.
if the request is POST it obtains the username and password, uses the authenticate function and saves it in a variable if it is true it uses the login function and redirects to the application of the specific user.

    Args:
        request

    Returns:
        return redirect to appfor user or render to register
    """

    if request.method == 'GET':
        context = ''
        return render(request, 'registration/login.html', {'context': context})
    elif request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(f'/application/{user.uuid}')
        else:
            context = {}
            messages.error(request, 'Usuario o contraña incorrectos')
            return render(request, 'registration/login.html', {'context': context})


def logout_view(request):
    logout(request)
    return redirect('personal_finance:login')


def application(request, uuid):
    """"
    this function uses the get_object_or_404 function to get a user or a 404, filters the transactions and categories to show the ones specific to that user.

    Keyword arguments: request, uuid of user
    Return: returns a render of the html application and sends the user by context
    """

    all_messages = messages.get_messages(request)
    for _ in all_messages:
        pass
    user = get_object_or_404(User, pk=uuid)
    transactions = Transaction.objects.filter(user_uuid=user.uuid)
    categories = Category.objects.filter(user=user.uuid)
    return render(request, 'application.html', {'user': user, 'transactions': transactions, 'categories': categories})


def create_category(request):
    """
    this function validates if the user is authenticated, if the condition is met it gets the category and creates a new one, then redirects to the same application of the user, if the condition is not met it redirects to the registry.

    Args:
        request: request

    Returns:
        redirect to aplication.html or register.html
    """

    if(request.user.is_authenticated):
        category = request.POST.get('category', '')
        if category and str(category) != "":
            Category.objects.create(category_name=category, user=request.user)
        else:
            messages.error(request, 'Las Categorias no pueden estar vacias')
        return redirect(f'/application/{request.user.uuid}')
    return redirect('personal_finance:login')


def create_transaction(request):
    """sumary_line
        this function validates if the user is authenticated, if it meets the condition it gets the form fields and creates a new transaction, then redirects to the same application of the user, if it does not meet the condition it redirects to the registry. 

    Return: redirection to app or register
    """

    if(request.user.is_authenticated):
        select = request.POST.get('select', '')
        amount = request.POST.get('value-form', '')
        title = request.POST.get('title-form', '')
        category = request.POST.get('select-category', '')

        if select and amount and title and category and str(select) != "" and str(amount) != "" and str(title) != "" and str(category) != "":
            Transaction.objects.create(
                type=select, amount=amount, user_uuid=request.user, category=list(Category.objects.filter(pk=category))[0], name=title)
            messages.success(request, f"añadida transacción {title}")
        else:
            messages.error(request, 'Debe llenar todos los campos')
        return redirect(f'/application/{request.user.uuid}')
    return redirect('personal_finance:login')

personal_finance/templates/application.html
{% extends "layout.html" %}


{% block registration %}
<a class="nav-link" href="{% url 'personal_finance:logout' %}">Logout</a>
{% endblock %}


{% block content %}

{% load personal_finance_extras %}
<div class="body-application">
  <header
    id="header-budget"
    class="bg-dark text-center text-light py-4 mt-5 border border-dark border-3 rounded-2"
  >
    <h1 class="mb-3">Personal Budget</h1>
    <section id="header-show-budget">
      <article class="flex-budget text-success" id="income">
        <h4 id="income-text">Income</h4>
        <p class="flex-end" id="income-value">{{user.uuid|calculate_income_total}}</p>
      </article>
      <article class="flex-budget text-danger" id="expenditures">
        <h4 id="expenditures-text">Expenditures</h4>
        <p id="expenditures-value">{{user.uuid|calculate_expense_total}}</p>
      </article>
      <article class="flex-budget" class="flex" id="available">
        <h3 class="h1">Available</h3>
        <p>{{user.uuid|get_user_owed_total_amount}}</p>
      </article>
    </section>
  </header>
  <section id="section-form" class="mt-3">
    <form id="form-category" action="{% url 'personal_finance:create_category' %}" method="POST"  class="d-flex align-items-center justify-content-center gap-4 py-2 mb-3 bg-success rounded-2">
      {% csrf_token %}
      <label for="category" class='text-light'>ADD CATEGORY</label>
      <input class="form-control" type="text" name="category" id="category" placeholder="Add Category" />
      <button type="submit" class="btn btn-primary">ADD</button>
    </form>
    <form
      method="POST"
      action="{% url 'personal_finance:create_transaction' %}"
      class="row mx-auto bg-secondary ms-3 pe-3 rounded-1"
      style="place-items: center; gap: 10px; padding: 1em 0;"
    >
    {% csrf_token %}
    <select 
      name="select-category" id="select" 
      style="width: 76px;"
      class="col-1 ms-4 bg-dark text-light border border-1 border-light rounded-2 p-1">
      {% for category in categories %}
        <option value={{category.id}}>{{category.category_name}}</option>
      {% endfor %}
    </select>
      <input
        class="col-3 input-title"
        type="text"
        name="title-form"
        id="title-form"
        placeholder="Enter the title"
      />
      <input
        class="col-6 input-value"
        type="text"
        name="value-form"
        id="value-form"
        placeholder="Enter the value"
      />
      <select 
      name="select" id="select" 
      style="width: 76px;"
      class="col-1 ms-4 bg-dark text-light border border-1 border-light rounded-2 p-1">
        <option value=0>+</option>
        <option value=1>-</option>
      </select>
      <button 
      type="submit" 
      style="width:80px"
      class="btn btn-success rounded-circle col-1">
        <i class="bi bi-check-circle"></i>
      </button>
    </form>
  </section>
  </section>
  <section class="row" id="show-badget">
    <section class="col-6 my-5" id="income">
      <h3 class="text-center text-success">Income</h3>
      <table class="table caption-top">
        <thead>
          <tr class="table-success">
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Amount</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for transaction in transactions %}
          {% if transaction.type == 0 %}
          <tr>
            <th scope="row">{{transaction.budget_id}}</th>
            <td>{{transaction.name}}</td>
            <td>{{transaction.amount}}</td>
            <td>
              <a class="fas fa-edit px-2"></a>
              <a class="fas fa-trash px-2 text-danger"></a>
            </td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </section>
    <section  class=" col-6 my-5" id="expenditure">
      <h3 class=" text-center text-danger">expenditure</h3>
      <table class="table caption-top">
        <thead>
          <tr class="table-danger">
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Amount</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for transaction in transactions %}
          {% if transaction.type == 1 %}
          <tr>
            <th scope="row">{{transaction.budget_id}}</th>
            <td>{{transaction.name}}</td>
            <td>{{transaction.amount}}</td>
            <td>
              <a class="fas fa-edit px-2"></a>
              <a class="fas fa-trash px-2 text-danger"></a>
            </td>
          </tr>
          {% endif %}
          {% endfor %}
        </tbody>
      </table>
    </section>
  </section>
</div>

{% endblock %}

personal_finance/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Personal Finance</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css/' %}" />
    <script
      src="https://kit.fontawesome.com/aaa1d1b991.js"
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">Home</a>
        <div class="navbar-nav d-flex flex-row ms-3">
          {% block registration %}
          <a class="nav-link me-3" href="/">Register</a>
          <a class="nav-link" href="{% url 'personal_finance:login' %}">Login</a>
          {% endblock %}
        </div>
      </div>
    </nav>
    <div class="container">
      {% if messages %} {% for message in messages %}
      {% if message.level == 25 %}
        <div class="alert alert-success">{{message}}</div>
      {% endif %}
      {% if message.level == 40 %}
        <div class="alert alert-danger">{{message}}</div>
      {% endif %}
      {% endfor %} {% endif %} {% block content %} {% endblock %}
    </div>
    <footer class="bg-dark">
      <div class="d-flex justify-content-evenly content-footer">
        <div class="text-light div-footer">
          <h3>Personal Budget</h3>
        </div>
        <div class="text-light div-footer">
          <h5>Personal Budget</h5>
          <p class="p-footer text-justify">
            By Deiver Vazquez, Isaac Benavidez and Jhonatan Alvarez. Copyright 2022. All rights reserved CAR IV LSV-TECH
          </p>
        </div>
        <p class="p-socialmedia text-light">Follow us:</p>
        <div class="d-flex justify-content-center text-light div-footer">
          <div class="div-icons">
            <a
              href="https://www.facebook.com/lsvtechcolombia11/"
              target="_blank"
              class="fab fa-facebook-f"
            ></a>
          </div>
          <div class="div-icons">
            <a
              href="https://www.instagram.com/lsv_tech/?hl=es"
              target="_blank"
              class="fab fa-instagram"
            ></a>
          </div>
          <div class="div-icons">
            <a
              href="https://www.youtube.com/channel/UC5gbK6qQflBM0fEObgEyYvw"
              target="_blank"
              class="fab fa-youtube"
            ></a>
          </div>
          <div class="div-icons">
            <a
              href="https://twitter.com/techlsv?lang=es"
              target="_blank"
              class="fab fa-twitter"
            ></a>
          </div>
        </div>
      </div>
      <div class="copy border-top">
        <p class="text-light text-center copy-text">
          &copy; 2022 Personal Budget
        </p>
      </div>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

personal_finance/templates/register.html
{% extends "layout.html"%}
{% block content %}
<div class="container d-grid body-aplication" style="width: 100%; place-items: center;">
  <div class="bg-dark px-5 py-2 rounded-3" style='width: 100%%;'>
    <h1 class="text-light text-center">Registration Form</h1>
    <form class="form" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <div class="d-grid gap-2 py-3">
        <button type="submit" class="btn btn-primary" id="submit">Submit</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}